const types = {
  SET_INFO_START: "SET_INFO",
  SET_INFO_SUCCESS: "SET_INFO_SUCCESS",

  GET_ALL_ITEMS_START: "GET_ALL_ITEMS_START",
  GET_ALL_ITEMS_SUCCESS: "GET_ALL_ITEMS_SUCCESS",

  UPDATE_INFO: "UPDATE_INFO",
  DELETE_ITEM: "DELETE_ITEM",

  ADD_ITEM: "ADD_ITEM",
  ADD_ITEM_SUCCESS: "ADD_ITEM_SUCCESS",

  NO_DATA_AVAILABLE: "NO_DATA_AVAILABLE",
};

export default types;
